name = "xr-publisher"
main = "src/worker.js"
compatibility_date = "2024-11-04"
compatibility_flags = ["nodejs_compat"]
account_id = "95d5ca589c39bf4189b080cfc8417c8e"

kv_namespaces = [
    { binding = "VISIT_COUNTS", id = "2f939c48d431442ab95dedf8a354fe71" }
]

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/5 * * * *"]

[[durable_objects.bindings]]
name = "WORLD_REGISTRY"
class_name = "WorldRegistryDO"

[[durable_objects.bindings]]
name = "USER_AUTH"
class_name = "UserAuthDO"

[[durable_objects.bindings]]
name = "CHARACTER_REGISTRY"
class_name = "CharacterRegistryDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WorldRegistryDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserAuthDO"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["CharacterRegistryDO"]

[vars]
ENVIRONMENT = "production"
WORLD_BUCKET_URL = "https://xr-publisher.95d5ca589c39bf4189b080cfc8417c8e.r2.cloudflarestorage.com"

[[r2_buckets]]
binding = "WORLD_BUCKET"
bucket_name = "xr-publisher-bucket"
preview_bucket_name = "xr-publisher-bucket-preview"

[env.production]
vars = { ENVIRONMENT = "production" }